mutation CreateEuWebPresence {
  marketWebPresenceCreate(
    marketId: "gid://shopify/Market/109765787992"
    webPresence: {
      defaultLocale: "en"
      alternateLocales: ["de", "fr", "es", "it", "nl"]
      subfolderSuffix: "eu"
    }
  ) {
    userErrors {
      field
      message
      code
    }
    market {
      id
      name
      webPresence {
        id
        subfolderSuffix
        defaultLocale {
          locale
        }
        alternateLocales {
          locale
        }
        rootUrls {
          locale
          url
        }
      }
    }
  }
}
